import type { Puzzle } from "../types";

export const puzzles: Puzzle[] = [
  {
    id: "puzzle-001",
    fen: "rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq g3 0 2",
    sideToMove: "b",
    solution: ["d8h4"],
    theme: "Matto in 1",
    difficulty: "base",
    hint: "Il re bianco ha una diagonale scoperta.",
    explanation: "La donna va in h4 e dà matto perché il re non ha case né difese utili.",
  },
  {
    id: "puzzle-002",
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
    sideToMove: "w",
    solution: ["h5f7"],
    theme: "Matto in 1",
    difficulty: "base",
    hint: "Il punto f7 è difeso dall'alfiere.",
    explanation: "Qxf7# sfrutta la pressione combinata di donna e alfiere sul re nero.",
  },
  {
    id: "puzzle-003",
    fen: "r3k2r/pp3ppp/8/3N4/8/8/PP3PPP/R3K2R w KQkq - 0 1",
    sideToMove: "w",
    solution: ["d5c7"],
    theme: "Forchetta",
    difficulty: "base",
    hint: "Il cavallo può dare scacco e attaccare una torre.",
    explanation: "Nc7+ attacca il re e la torre a8: dopo la risposta al check, il Bianco vince materiale.",
  },
  {
    id: "puzzle-004",
    fen: "4r1k1/5ppp/8/8/8/8/4RPPP/6K1 w - - 0 1",
    sideToMove: "w",
    solution: ["e2e8"],
    theme: "Infilata",
    difficulty: "intermedio",
    hint: "La torre può entrare in ottava.",
    explanation: "Rxe8+ elimina la torre attiva e trasforma la posizione in un finale favorevole.",
  },
  {
    id: "puzzle-005",
    fen: "6k1/P5pp/8/8/8/8/6PP/6K1 w - - 0 1",
    sideToMove: "w",
    solution: ["a7a8q"],
    theme: "Promozione",
    difficulty: "base",
    hint: "Il pedone è a un passo dalla trasformazione.",
    explanation: "a8=Q crea una donna nuova e porta il Bianco in vantaggio decisivo.",
  },
  {
    id: "puzzle-006",
    fen: "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    sideToMove: "w",
    solution: ["d3c3"],
    theme: "Finale di pedoni",
    difficulty: "intermedio",
    hint: "Cerca l'opposizione, non spingere subito.",
    explanation: "Kc3 mantiene l'opposizione e aiuta il pedone a progredire senza concedere il blocco.",
  },
  {
    id: "puzzle-007",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    sideToMove: "w",
    solution: ["e1e8"],
    theme: "Finale torre",
    difficulty: "intermedio",
    hint: "La torre cerca attività dietro al re.",
    explanation: "Re8+ attiva la torre con scacco e forza il re nero in una posizione più passiva.",
  },
  {
    id: "puzzle-008",
    fen: "4k3/8/8/3q4/8/4N3/8/4K3 w - - 0 1",
    sideToMove: "w",
    solution: ["e3d5"],
    theme: "Pezzo indifeso",
    difficulty: "base",
    hint: "Il cavallo può prendere il pezzo più prezioso.",
    explanation: "Nxd5 vince la donna indifesa e cambia subito il bilancio materiale.",
  },
  {
    id: "puzzle-009",
    fen: "4k3/8/8/8/1b6/2N5/8/4K3 w - - 0 1",
    sideToMove: "w",
    solution: ["c3b5"],
    theme: "Attacco doppio",
    difficulty: "intermedio",
    hint: "Il cavallo attacca re e alfiere da una casa centrale.",
    explanation: "Nb5 crea una minaccia doppia e costringe il Nero a rispondere al problema più urgente.",
  },
  {
    id: "puzzle-010",
    fen: "6k1/5ppp/8/8/8/8/4qPPP/4R1K1 w - - 0 1",
    sideToMove: "w",
    solution: ["e1e8"],
    theme: "Difesa",
    difficulty: "avanzato",
    hint: "Uno scacco può togliere tempo alla minaccia avversaria.",
    explanation: "Re8+ crea controgioco immediato e permette al Bianco di non subire passivamente la pressione della donna.",
  },
];

export const puzzleThemes = [...new Set(puzzles.map((puzzle) => puzzle.theme))];
